# Generated by Django 4.1.2 on 2025-04-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_tech', '0005_carrito_remove_cargo_roles_remove_cliente_debe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_documento',
        ),
    ]
