# Generated by Django 4.1.2 on 2025-04-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_tech', '0006_remove_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='rol',
            field=models.CharField(choices=[('Empleado', 'Empleado'), ('Administrador', 'Administrador')], default='Empleado', max_length=50),
        ),
    ]
