# Generated by Django 4.1.2 on 2025-04-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_tech', '0007_alter_cargo_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
