# Generated by Django 5.1.7 on 2025-04-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_tech', '0009_remove_detallefactura_producto_remove_factura_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
    ]
