# Generated by Django 5.1.7 on 2025-04-07 07:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_tech', '0010_remove_factura_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='producto_nombre',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bar_tech.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar_tech.factura'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bar_tech.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
