# Generated by Django 5.1.7 on 2025-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_tech', '0012_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Cervezas'), ('2', 'Aguardiente'), ('3', 'Gaseosas'), ('4', 'Alta'), ('5', 'Ron'), ('6', 'Otros')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
