# Generated by Django 5.1.7 on 2025-04-07 12:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_tech', '0013_alter_producto_categoria_delete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='abonos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='No se permiten caracteres especiales. Solo letras, números y espacios.', regex='^[a-zA-Z0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='deben',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='No se permiten caracteres especiales. Solo letras, números y espacios.', regex='^[a-zA-Z0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='No se permiten caracteres especiales. Solo letras, números y espacios.', regex='^[a-zA-Z0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='mesa',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='No se permiten caracteres especiales. Solo letras, números y espacios.', regex='^[a-zA-Z0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='La clave solo puede contener letras, números y caracteres especiales.', regex='^[a-zA-Z0-9@#$%^&+=]*$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El documento debe ser un número válido.', regex='^\\d{5,20}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe ser válido.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
